import { Header } from '@/components/Header';
import { Box, Container, Divider, Drawer, Grid, Link, List, ListItem, ListItemButton, ListItemIcon, ListItemText, ThemeProvider, Toolbar, Typography, createTheme } from '@mui/material';
import InboxIcon from '@mui/icons-material/Inbox';
import Image from 'next/image';
import green from '@mui/material/colors/green';
import LogoImage from '../../public/lantana_logo_new.png';

export const metadata = {
  title: 'Lantana',
  description: 'Generated by create next app',
};

const drawerWidth = 240;

const theme = createTheme({
  palette: {
    // mode: 'dark',
    primary: green,
  },
});


export default function EnterpriseLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThemeProvider theme={theme}>

      <Drawer
        sx={{
          width: drawerWidth,
          flexShrink: 0,
          '& .MuiDrawer-paper': {
            width: drawerWidth,
            boxSizing: 'border-box',
            // marginTop: '120px'
          }
        }}
        variant="permanent"
        anchor="left"
      >
        <Grid container sx={{ display: 'flex', m: 1 }} justifyContent="center" >
          <Link href="/">
            <Image src={LogoImage} height={60} alt="Lantana" />
          </Link>
        </Grid>
        <Divider />
        <List>

          {/* <Link href="/">
            <ListItem key={'home'} disablePadding>
              <ListItemButton>
                <ListItemIcon>
                  <InboxIcon />
                </ListItemIcon>
                <ListItemText primary={'Home'} />
              </ListItemButton>
            </ListItem>
          </Link> */}
          <Link href="/enterprise/dashboard">
            <ListItem key={'dashboard'} disablePadding>
              <ListItemButton>
                <ListItemIcon>
                  <InboxIcon />
                </ListItemIcon>
                <ListItemText primary={'Dashboard'} />
              </ListItemButton>
            </ListItem>
          </Link>
          <Link href="/enterprise/feed">
            <ListItem key={'causes'} disablePadding>
              <ListItemButton>
                <ListItemIcon>
                  <InboxIcon />
                </ListItemIcon>
                <ListItemText primary={'Causes'} />
              </ListItemButton>
            </ListItem>
          </Link>
        </List>
        <Divider />

        <Box style={{ marginTop: `auto` }} mb={2}>
          <Divider />
          <Typography variant="h5" m={3}>
            SynTech
          </Typography>
        </Box>


      </Drawer>
      <Container sx={{ mt: 4 }}>


        {children}
      </Container>
    </ThemeProvider >
  );
}
