import { Header } from '@/components/Header';
import { Inter } from 'next/font/google';

import Container from '@mui/material/Container';

export const metadata = {
  title: 'Lantana',
  description: 'Generated by create next app',
};

export default function SocialLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <Header />
      <Container maxWidth="lg" sx={{ marginTop: '50px' }}>
        {children}
      </Container>
    </div>
  );
}
