import Container from '@mui/material/Container';

export const metadata = {
  title: 'Lantana',
  description: 'Generated by create next app',
};

export default function SocialLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Container maxWidth="lg" sx={{ margin: '20px' }}>
      {children}
    </Container>
  );
}
