on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

env:
  CI: true
  NODE_ENV: test
  NEXT_PUBLIC_PN_PROJECT_ID: ${{ secrets.PN_PROJECT_ID }}
  NEXT_PUBLIC_PN_CLIENT_KEY: ${{ secrets.PN_CLIENT_KEY }}
  NEXT_PUBLIC_PN_APP_ID: ${{ secrets.PN_APP_ID }}
  NFT_STORAGE_TOKEN: ${{ secrets.NFT_STORAGE_TOKEN }}
  WEB3_STORAGE_TOKEN: ${{ secrets.WEB3_STORAGE_TOKEN }}
  TEST_PRIVATE_KEY: ${{ secrets.TEST_PRIVATE_KEY }}
  ALCHEMY_API_TOKEN_MUMBAI: ${{ secrets.TEST_PRIVATE_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.x
          cache: yarn
      - name: Install
        run: yarn install
      - name: Test
        run: yarn run test
      - name: Build
        run: yarn run build
      - name: Build Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: false
